# Generated by Django 3.1.4 on 2020-12-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_auto_20201223_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('description', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
