# Generated by Django 3.1.4 on 2020-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0004_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quadrant',
            field=models.IntegerField(null=True),
        ),
    ]
