# Generated by Django 3.1.4 on 2020-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0005_auto_20201230_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
