from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='objectives-home'),
    path('home/', views.home, name='objectives-home'),
    path('tasks/', views.tasks, name='objectives-tasks'),
    path('new_task', views.new_task, name='objectives-new-task'),
    path('update_task/<str:pk>/', views.update_task, name='objectives-update-task'),
    path('delete_task/<str:pk>/', views.delete_task, name='objectives-delete-task'),
    path('properties/', views.properties, name='objectives-properties'),
    path('new_property/', views.new_property, name='objectives-new-property'),
    path('update_property/<str:pk>/', views.update_property, name='objectives-update-property'),
    path('delete_property/<str:pk>/', views.delete_property, name='objectives-delete-property'),
    path('categories/', views.categories, name='objectives-categories'),
    path('new_category/', views.new_category, name='objectives-new-category'),
    path('update_category/<str:pk>/', views.update_category, name='objectives-update-category'),
    path('delete_category/<str:pk>/', views.delete_category, name='objectives-delete-category'),
    path('departments/', views.departments, name='objectives-departments'),
    path('new_department/', views.new_department, name='objectives-new-department'),
    path('update_department/<str:pk>/', views.update_department, name='objectives-update-department'),
    path('delete_department/<str:pk>/', views.delete_department, name='objectives-delete-department'),
    path('people/', views.people, name='objectives-people'),
    path('new_person/', views.new_person, name='objectives-new-person'),
    path('update_person/<str:pk>/', views.update_person, name='objectives-update-person'),
    path('delete_person/<str:pk>/', views.delete_person, name='objectives-delete-person'),
    path('priorities/', views.priorities, name='objectives-priorities'),
    path('new_priority/', views.new_priority, name='objectives-new-priority'),
    path('update_priority/<str:pk>/', views.update_priority, name='objectives-update-priority'),
    path('delete_priority/<str:pk>/', views.delete_priority, name='objectives-delete-priority'),
    path('statuses/', views.statuses, name='objectives-statuses'),
    path('new_status/', views.new_status, name='objectives-new-status'),
    path('update_status/<str:pk>/', views.update_status, name='objectives-update-status'),
    path('delete_status/<str:pk>/', views.delete_status, name='objectives-delete-status')
]
